name: Continuous Integration
on: [push, pull_request, release]
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - run: make --file ./plugins/dreck/makefile
      shell: bash
    - if: github.event_name == 'release' && github.event.action == 'created'
      uses: softprops/action-gh-release@v1
      with:
        files: SPECIFY FILE PATHS HERE
